const GET_HOMES_LOADING = "GET_HOMES_LOADING";
const GET_HOMES_SUCCESS = "GET_HOMES_SUCCESS";
const GET_HOMES_FAILED = "GET_HOMES_FAILED";

const ADD_HOME_LOADING = "ADD_HOME_LOADING";
const ADD_HOME_SUCCESS = "ADD_HOME_SUCCESS";
const ADD_HOME_FAILED = "ADD_HOME_FAILED";

const DELETE_HOME_FAILED = "DELETE_HOME_FAILED";

const SEARCH_MEMBER_LOADING = "SEARCH_MEMBER_LOADING";
const SEARCH_MEMBER_SUCCESS = "SEARCH_MEMBER_SUCCESS";
const SEARCH_MEMBER_FAILED = "SEARCH_MEMBER_FAILED";
const RESET_SEARCH_LIST = "RESET_SEARCH_LIST";

const ADD_MEMBER_LOADING = "ADD_MEMBER_LOADING";
const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
const ADD_MEMBER_FAILED = "ADD_MEMBER_FAILED";
const RESET_ADD_MEMBER_STATUS = "RESET_ADD_MEMBER_STATUS";

export {
    GET_HOMES_LOADING,
    GET_HOMES_SUCCESS,
    GET_HOMES_FAILED,

    ADD_HOME_LOADING,
    ADD_HOME_SUCCESS,
    ADD_HOME_FAILED,

    DELETE_HOME_FAILED,

    SEARCH_MEMBER_LOADING,
    SEARCH_MEMBER_SUCCESS,
    SEARCH_MEMBER_FAILED,
    RESET_SEARCH_LIST,

    ADD_MEMBER_LOADING,
    ADD_MEMBER_SUCCESS,
    ADD_MEMBER_FAILED,
    RESET_ADD_MEMBER_STATUS,
}