const GET_HOMES_LOADING = "GET_HOMES_LOADING";
const GET_HOMES_SUCCESS = "GET_HOMES_SUCCESS";
const GET_HOMES_FAILED = "GET_HOMES_FAILED";

const ADD_HOME_LOADING = "ADD_HOME_LOADING";
const ADD_HOME_SUCCESS = "ADD_HOME_SUCCESS";
const ADD_HOME_FAILED = "ADD_HOME_FAILED";

const DELETE_HOME_FAILED = "DELETE_HOME_FAILED";

export {
    GET_HOMES_LOADING,
    GET_HOMES_SUCCESS,
    GET_HOMES_FAILED,

    ADD_HOME_LOADING,
    ADD_HOME_SUCCESS,
    ADD_HOME_FAILED,

    DELETE_HOME_FAILED
}