const USER_LOADING = "USER_LOADING";
const USER_SUCCESS = "USER_SUCCESS";
const USER_FAILED = "USER_FAILED";
const RESET_USER = "RESET_USER";

export {
    USER_LOADING,
    USER_SUCCESS,
    USER_FAILED,
    RESET_USER
}